/*
 * Aurora 编译器中端 - 内联器
 * 支持 100+ 内联操作
 */

#ifndef AURORA_INLINE_H
#define AURORA_INLINE_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../frontend/aurora_ast.h"
#include "aurora_ir.h"

/* 内联类型 */
typedef enum {
    INLINE_NONE,
    INLINE_ALWAYS,
    INLINE_HINT,
    INLINE_AUTO,
    INLINE_FORCED,
    INLINE_RECURSIVE,
    INLINE_MUTUAL_RECURSIVE,
    INLINE_TAIL,
    INLINE_HEAD,
    INLINE_PARTIAL,
    INLINE_FULL,
    INLINE_CLONE,
    INLINE_SPECIALIZE,
    INLINE_MONOMORPHIZE,
    INLINE_DEVVIRTUALIZE,
    INLINE_COUNT
} InlineType;

/* 内联决策 */
typedef struct InlineDecision {
    InlineType type;
    int should_inline;
    int cost;
    int benefit;
    int threshold;
    int size_before;
    int size_after;
    int growth;
    int max_growth;
    int call_count;
    int hotness;
    int is_hot;
    int is_cold;
    int is_recursive;
    int is_virtual;
    int is_variadic;
    int has_side_effects;
    int has_loops;
    int has_branches;
    int has_recursion;
    int has_allocation;
    int has_io;
    int has_exceptions;
    int has_gotos;
    int has_labels;
    int has_computed_goto;
    int has_inline_asm;
    int has_builtins;
    int has_intrinsics;
    int has_atomics;
    int has_fences;
    int has_locks;
    int has_thread_local;
    int has_static;
    int has_global;
    int has_constant;
    int has_literal;
    int has_string;
    int has_array;
    int has_struct;
    int has_union;
    int has_enum;
    int has_pointer;
    int has_reference;
    int has_rvalue;
    int has_lvalue;
    int has_xvalue;
    int has_prvalue;
    int has_glvalue;
    int has_void;
    int has_bool;
    int has_char;
    int has_short;
    int has_int;
    int has_long;
    int has_long_long;
    int has_float;
    int has_double;
    int has_long_double;
    int has_complex;
    int has_imaginary;
    int has_decimal;
    int has_fixed;
    int has_bigint;
    int has_rational;
    int has_decimal32;
    int has_decimal64;
    int has_decimal128;
    int has_bfloat16;
    int has_float16;
    int has_float128;
    int has_int8;
    int has_int16;
    int has_int32;
    int has_int64;
    int has_int128;
    int has_uint8;
    int has_uint16;
    int has_uint32;
    int has_uint64;
    int has_uint128;
    int has_size_t;
    int has_ssize_t;
    int has_ptrdiff_t;
    int has_intptr_t;
    int has_uintptr_t;
    int has_max_align_t;
    int has_wchar_t;
    int has_char16_t;
    int has_char32_t;
    int has_char8_t;
    int has_nullptr_t;
    int has_byte;
    int has_any;
    int has_variant;
    int has_optional;
    int has_expected;
    int has_result;
    int has_future;
    int has_promise;
    int has_channel;
    int has_stream;
    int has_iterator;
    int has_generator;
    int has_coroutine;
    int has_thread;
    int has_mutex;
    int has_condvar;
    int has_semaphore;
    int has_barrier;
    int has_rwlock;
    int has_spinlock;
    int has_atomic_type;
    int has_future_type;
    int has_promise_type;
    int has_channel_type;
    int has_stream_type;
    int has_iterator_type;
    int has_generator_type;
    int has_coroutine_type;
    int has_thread_type;
    int has_mutex_type;
    int has_condvar_type;
    int has_semaphore_type;
    int has_barrier_type;
    int has_rwlock_type;
    int has_spinlock_type;
    int has_atomic_type_type;
    int line;
    int column;
    void* ast_node;
    void* ir_node;
    struct InlineDecision* next;
} InlineDecision;

/* 内联器 */
typedef struct Inliner {
    int initialized;
    InlineType default_type;
    int max_inline_size;
    int max_inline_depth;
    int max_inline_count;
    int max_total_size;
    int max_growth_factor;
    int hot_threshold;
    int cold_threshold;
    void* decisions;
    int decision_count;
    int decision_capacity;
    void* decision_table;
    void* call_sites;
    int call_site_count;
    void* function_cache;
    int cache_count;
    int cache_hits;
    int cache_misses;
    void* clone_cache;
    int clone_count;
    void* specialization_cache;
    int specialization_count;
    int current_file;
    char* current_file_name;
    int current_module;
    char* current_module_name;
    int strict_mode;
    int aggressive_mode;
    int conservative_mode;
    int allow_unsafe;
    int allow_undefined_behavior;
    int allow_side_effects;
    int allow_io;
    int allow_allocation;
    int allow_recursion;
    int allow_mutual_recursion;
    int allow_virtual;
    int allow_variadic;
    int allow_exceptions;
    int allow_gotos;
    int allow_labels;
    int allow_computed_goto;
    int allow_inline_asm;
    int allow_builtins;
    int allow_intrinsics;
    int allow_atomics;
    int allow_fences;
    int allow_locks;
    int allow_thread_local;
    int allow_static;
    int allow_global;
    int max_iterations;
    int error_count;
    int warning_count;
    void* errors;
    int error_capacity;
    void* warnings;
    int warning_capacity;
    int debug_mode;
    int trace_mode;
    int profile_mode;
    int log_level;
    FILE* log_file;
    double start_time;
    double total_time;
    long long functions_inlined;
    long long call_sites_processed;
    long long decisions_made;
    long long decisions_accepted;
    long long decisions_rejected;
    long long clones_created;
    long long specializations_created;
    long long monomorphizations;
    long long devirtualizations;
    long long recursive_inlined;
    long long mutual_recursive_inlined;
    long long tail_inlined;
    long long head_inlined;
    long long partial_inlined;
    long long full_inlined;
    long long always_inlined;
    long long hint_inlined;
    long long auto_inlined;
    long long forced_inlined;
    long long hot_inlined;
    long long cold_skipped;
    long long size_limited;
    long long depth_limited;
    long long count_limited;
    long long growth_limited;
    long long side_effects_skipped;
    long long loops_skipped;
    long long branches_skipped;
    long long recursion_skipped;
    long long allocation_skipped;
    long long io_skipped;
    long long exceptions_skipped;
    long long gotos_skipped;
    long long labels_skipped;
    long long computed_goto_skipped;
    long long inline_asm_skipped;
    long long builtins_skipped;
    long long intrinsics_skipped;
    long long atomics_skipped;
    long long fences_skipped;
    long long locks_skipped;
    long long thread_local_skipped;
    long long static_skipped;
    long long global_skipped;
    long long virtual_skipped;
    long long variadic_skipped;
    long long bytes_saved;
    long long lines_saved;
    long long characters_saved;
} Inliner;

/* 函数声明 */
int inline_func_000(Inliner* inliner, void* call_site);
int inline_func_001(Inliner* inliner, void* call_site);
int inline_func_002(Inliner* inliner, void* call_site);
int inline_func_003(Inliner* inliner, void* call_site);
int inline_func_004(Inliner* inliner, void* call_site);
int inline_func_005(Inliner* inliner, void* call_site);
int inline_func_006(Inliner* inliner, void* call_site);
int inline_func_007(Inliner* inliner, void* call_site);
int inline_func_008(Inliner* inliner, void* call_site);
int inline_func_009(Inliner* inliner, void* call_site);
int inline_func_010(Inliner* inliner, void* call_site);
int inline_func_011(Inliner* inliner, void* call_site);
int inline_func_012(Inliner* inliner, void* call_site);
int inline_func_013(Inliner* inliner, void* call_site);
int inline_func_014(Inliner* inliner, void* call_site);
int inline_func_015(Inliner* inliner, void* call_site);
int inline_func_016(Inliner* inliner, void* call_site);
int inline_func_017(Inliner* inliner, void* call_site);
int inline_func_018(Inliner* inliner, void* call_site);
int inline_func_019(Inliner* inliner, void* call_site);
int inline_func_020(Inliner* inliner, void* call_site);
int inline_func_021(Inliner* inliner, void* call_site);
int inline_func_022(Inliner* inliner, void* call_site);
int inline_func_023(Inliner* inliner, void* call_site);
int inline_func_024(Inliner* inliner, void* call_site);
int inline_func_025(Inliner* inliner, void* call_site);
int inline_func_026(Inliner* inliner, void* call_site);
int inline_func_027(Inliner* inliner, void* call_site);
int inline_func_028(Inliner* inliner, void* call_site);
int inline_func_029(Inliner* inliner, void* call_site);
int inline_func_030(Inliner* inliner, void* call_site);
int inline_func_031(Inliner* inliner, void* call_site);
int inline_func_032(Inliner* inliner, void* call_site);
int inline_func_033(Inliner* inliner, void* call_site);
int inline_func_034(Inliner* inliner, void* call_site);
int inline_func_035(Inliner* inliner, void* call_site);
int inline_func_036(Inliner* inliner, void* call_site);
int inline_func_037(Inliner* inliner, void* call_site);
int inline_func_038(Inliner* inliner, void* call_site);
int inline_func_039(Inliner* inliner, void* call_site);
int inline_func_040(Inliner* inliner, void* call_site);
int inline_func_041(Inliner* inliner, void* call_site);
int inline_func_042(Inliner* inliner, void* call_site);
int inline_func_043(Inliner* inliner, void* call_site);
int inline_func_044(Inliner* inliner, void* call_site);
int inline_func_045(Inliner* inliner, void* call_site);
int inline_func_046(Inliner* inliner, void* call_site);
int inline_func_047(Inliner* inliner, void* call_site);
int inline_func_048(Inliner* inliner, void* call_site);
int inline_func_049(Inliner* inliner, void* call_site);
int inline_func_050(Inliner* inliner, void* call_site);
int inline_func_051(Inliner* inliner, void* call_site);
int inline_func_052(Inliner* inliner, void* call_site);
int inline_func_053(Inliner* inliner, void* call_site);
int inline_func_054(Inliner* inliner, void* call_site);
int inline_func_055(Inliner* inliner, void* call_site);
int inline_func_056(Inliner* inliner, void* call_site);
int inline_func_057(Inliner* inliner, void* call_site);
int inline_func_058(Inliner* inliner, void* call_site);
int inline_func_059(Inliner* inliner, void* call_site);
int inline_func_060(Inliner* inliner, void* call_site);
int inline_func_061(Inliner* inliner, void* call_site);
int inline_func_062(Inliner* inliner, void* call_site);
int inline_func_063(Inliner* inliner, void* call_site);
int inline_func_064(Inliner* inliner, void* call_site);
int inline_func_065(Inliner* inliner, void* call_site);
int inline_func_066(Inliner* inliner, void* call_site);
int inline_func_067(Inliner* inliner, void* call_site);
int inline_func_068(Inliner* inliner, void* call_site);
int inline_func_069(Inliner* inliner, void* call_site);
int inline_func_070(Inliner* inliner, void* call_site);
int inline_func_071(Inliner* inliner, void* call_site);
int inline_func_072(Inliner* inliner, void* call_site);
int inline_func_073(Inliner* inliner, void* call_site);
int inline_func_074(Inliner* inliner, void* call_site);
int inline_func_075(Inliner* inliner, void* call_site);
int inline_func_076(Inliner* inliner, void* call_site);
int inline_func_077(Inliner* inliner, void* call_site);
int inline_func_078(Inliner* inliner, void* call_site);
int inline_func_079(Inliner* inliner, void* call_site);
int inline_func_080(Inliner* inliner, void* call_site);
int inline_func_081(Inliner* inliner, void* call_site);
int inline_func_082(Inliner* inliner, void* call_site);
int inline_func_083(Inliner* inliner, void* call_site);
int inline_func_084(Inliner* inliner, void* call_site);
int inline_func_085(Inliner* inliner, void* call_site);
int inline_func_086(Inliner* inliner, void* call_site);
int inline_func_087(Inliner* inliner, void* call_site);
int inline_func_088(Inliner* inliner, void* call_site);
int inline_func_089(Inliner* inliner, void* call_site);
int inline_func_090(Inliner* inliner, void* call_site);
int inline_func_091(Inliner* inliner, void* call_site);
int inline_func_092(Inliner* inliner, void* call_site);
int inline_func_093(Inliner* inliner, void* call_site);
int inline_func_094(Inliner* inliner, void* call_site);
int inline_func_095(Inliner* inliner, void* call_site);
int inline_func_096(Inliner* inliner, void* call_site);
int inline_func_097(Inliner* inliner, void* call_site);
int inline_func_098(Inliner* inliner, void* call_site);
int inline_func_099(Inliner* inliner, void* call_site);
Inliner* inliner_create();
void inliner_destroy(Inliner* inliner);
int inliner_init(Inliner* inliner);
int inliner_inline(Inliner* inliner, ASTNode* root);
int inliner_inline_ir(Inliner* inliner, IRModule* module);
int inliner_inline_file(Inliner* inliner, const char* filename);
InlineDecision* inline_decision_create(InlineType type);
void inline_decision_destroy(InlineDecision* decision);
int inliner_analyze_call_site(Inliner* inliner, void* call_site);
int inliner_evaluate_cost(Inliner* inliner, void* function);
int inliner_evaluate_benefit(Inliner* inliner, void* call_site);
int inliner_make_decision(Inliner* inliner, void* call_site);
int inliner_apply_inlining(Inliner* inliner, void* call_site);
int inliner_clone_function(Inliner* inliner, void* function);
int inliner_specialize_function(Inliner* inliner, void* function, void* types);
int inliner_monomorphize(Inliner* inliner, void* generic);
int inliner_devirtualize(Inliner* inliner, void* call_site);
int inliner_inline_recursive(Inliner* inliner, void* function);
int inliner_inline_mutual_recursive(Inliner* inliner, void* functions, int count);
int inliner_inline_tail(Inliner* inliner, void* call_site);
int inliner_inline_head(Inliner* inliner, void* call_site);
int inliner_inline_partial(Inliner* inliner, void* call_site);
int inliner_inline_full(Inliner* inliner, void* call_site);
int inliner_inline_always(Inliner* inliner, void* call_site);
int inliner_inline_hint(Inliner* inliner, void* call_site);
int inliner_inline_auto(Inliner* inliner, void* call_site);
int inliner_inline_forced(Inliner* inliner, void* call_site);
int inliner_check_size(Inliner* inliner, void* function);
int inliner_check_depth(Inliner* inliner, void* call_site);
int inliner_check_count(Inliner* inliner, void* function);
int inliner_check_growth(Inliner* inliner, void* call_site);
int inliner_check_hotness(Inliner* inliner, void* call_site);
int inliner_check_side_effects(Inliner* inliner, void* function);
int inliner_check_loops(Inliner* inliner, void* function);
int inliner_check_branches(Inliner* inliner, void* function);
int inliner_check_recursion(Inliner* inliner, void* function);
int inliner_check_allocation(Inliner* inliner, void* function);
int inliner_check_io(Inliner* inliner, void* function);
int inliner_check_exceptions(Inliner* inliner, void* function);
int inliner_check_gotos(Inliner* inliner, void* function);
int inliner_check_labels(Inliner* inliner, void* function);
int inliner_check_computed_goto(Inliner* inliner, void* function);
int inliner_check_inline_asm(Inliner* inliner, void* function);
int inliner_check_builtins(Inliner* inliner, void* function);
int inliner_check_intrinsics(Inliner* inliner, void* function);
int inliner_check_atomics(Inliner* inliner, void* function);
int inliner_check_fences(Inliner* inliner, void* function);
int inliner_check_locks(Inliner* inliner, void* function);
int inliner_check_thread_local(Inliner* inliner, void* function);
int inliner_check_static(Inliner* inliner, void* function);
int inliner_check_global(Inliner* inliner, void* function);
int inliner_check_virtual(Inliner* inliner, void* function);
int inliner_check_variadic(Inliner* inliner, void* function);
int inliner_verify(Inliner* inliner);
int inliner_report(Inliner* inliner);
int inliner_stats(Inliner* inliner);

#endif /* AURORA_INLINE_H */